name: baleen
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - faiss-gpu
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - cudatoolkit=11.3